### ISSUE TITLE
Fastpack?

### ISSUE THREAD

**Issue by denji** [tehcookies/bundlers-comparison#4]
* https://github.com/fastpack/fastpack

|                       |Fastpack|Webpack|Parcel<sup>*</sup>
|-----------------------|:------:|:-----:|:----:
|initial build          | **2.148s**  | 6.113s | 24.32s
|- [persistent cache](${docUrl('persistent-cache.html')}) | **0.176s**  | N/A | 14.88s
|- watch mode   | **0.074s**  | 0.612s  | 0.354s

**Comment by mkalygin** [comment]
@denji is it intended to be used for production? It reminds me [Pax](https://pax.js.org/) which is for development only. I can see a line in their README saying that Fastpack doesn't support production yet.
